export const customesModel = [
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(255)-555-0118",
    email: "jane@microsoft.com",
    counrty: "United state",
    status: "active",
  },
];
